springdoc:
  swagger-ui:
    enabled: true

logging:
  level:
    root: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.data.jpa.repository.query: DEBUG
    org.springframework.transaction: DEBUG
    com.gustoexpedition: DEBUG
  file:
    name: logs/gusto-backend.log

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gusto
    username: gusto
    password: gusto
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        show_sql: false
    open-in-view: false

LOG_FORMAT: PLAIN
LOG_PATH: ./logs
